import type { Vertical } from "./types";

// One entry per vertical. Adding a business type means adding an object here
// and nothing else — the renderer is driven entirely by `input`.

export const CLINIC: Vertical = {
  id: "clinic",
  label: "Clinic or healthcare",
  blurb: "Doctors, dentists, physio, veterinary, aesthetics",
  match: ["clinic", "health", "medical", "dental", "dentist", "doctor", "physio", "veterinar", "aesthetic", "hospital", "pharmac"],
  questions: [
    {
      id: "services_catalog",
      label: "Add your services and prices",
      help: "Upload a price list or paste it as text. You will review everything before it saves.",
      input: "catalog",
      catalog: {
        noun: "service list",
        itemNoun: "service",
        attributeHints: ["duration", "practitioner", "follow-up included"],
        pastePlaceholder: "Consultation 300, Cleaning 250, تبييض 900",
      },
      important: true,
    },
    {
      id: "services",
      label: "What do you treat or offer?",
      input: "list",
      placeholder: "Add a service…",
      important: true,
      prefillFrom: "identity.offerings",
    },
    {
      id: "takes_appointments",
      label: "Do you work by appointment?",
      input: "switch",
    },
    {
      id: "booking_channels",
      label: "How do people book?",
      input: "chips",
      options: ["Phone", "WhatsApp", "Online booking", "Walk-in", "Through reception"],
      allowCustom: true,
      showIf: { question: "takes_appointments", equals: true },
    },
    {
      id: "wait_time",
      label: "How soon can someone usually be seen?",
      help: "So your AI can set expectations honestly.",
      input: "single_select",
      options: ["Same day", "Within 2–3 days", "About a week", "More than a week"],
      showIf: { question: "takes_appointments", equals: true },
    },
    {
      id: "accepts_insurance",
      label: "Do you accept insurance?",
      input: "switch",
    },
    {
      id: "insurers",
      label: "Which ones?",
      input: "chips",
      options: ["Self-pay only"],
      allowCustom: true,
      placeholder: "Add an insurer you accept…",
      showIf: { question: "accepts_insurance", equals: true },
    },
    {
      id: "consultation_fee",
      label: "What does a consultation cost?",
      input: "price_range",
    },
    {
      id: "cancellation_notice",
      label: "How much notice do you need to cancel?",
      input: "single_select",
      options: ["No policy", "24 hours", "48 hours", "Same-day charge applies"],
    },
    {
      id: "emergencies",
      label: "What should someone with an urgent problem be told?",
      help: "Your AI will use these words when a message sounds urgent.",
      input: "long_text",
      placeholder: "Call us on … or go to the nearest emergency room.",
      important: true,
    },
  ],
};

export const DISTRIBUTOR: Vertical = {
  id: "distributor",
  label: "Distributor or wholesale",
  blurb: "Selling in bulk to shops, trade or businesses",
  match: ["distribut", "wholesale", "supplier", "import", "export", "trade", "b2b", "manufactur"],
  questions: [
    {
      id: "products_catalog",
      label: "Add your product list",
      help: "Upload your catalog or price list, or paste it as text. You will review everything before it saves.",
      input: "catalog",
      catalog: {
        noun: "product list",
        itemNoun: "product",
        attributeHints: ["unit", "case size", "wholesale price", "MOQ"],
        pastePlaceholder: "Olive oil 1L — 45/case of 12, Rice 5kg — 30",
      },
      important: true,
    },
    {
      id: "products",
      label: "What do you supply?",
      input: "list",
      placeholder: "Add a product line…",
      important: true,
      prefillFrom: "identity.offerings",
    },
    {
      id: "has_moq",
      label: "Do you have a minimum order?",
      input: "switch",
    },
    {
      id: "moq",
      label: "What's the minimum?",
      input: "price_range",
      help: "Units or value — whichever you actually quote.",
      showIf: { question: "has_moq", equals: true },
    },
    {
      id: "lead_time",
      label: "How long does a standard order take?",
      input: "single_select",
      options: ["Same day", "1–3 days", "About a week", "2 weeks or more", "Depends on the item"],
      important: true,
    },
    {
      id: "fulfilment",
      label: "How do orders reach the customer?",
      input: "chips",
      options: ["We deliver", "Customer pickup", "Third-party courier", "Freight"],
      allowCustom: true,
    },
    {
      id: "delivery_areas",
      label: "Where do you deliver?",
      input: "chips",
      options: [],
      allowCustom: true,
      placeholder: "Add a city, region or country…",
      prefillFrom: "policies.shipping",
    },
    {
      id: "sells_to",
      label: "Who can buy from you?",
      input: "single_select",
      options: ["Trade only", "Trade and individuals", "Anyone"],
      important: true,
    },
    {
      id: "credit_terms",
      label: "Do you offer credit terms?",
      input: "switch",
    },
    {
      id: "credit_terms_detail",
      label: "What terms?",
      input: "short_text",
      placeholder: "30 days for approved accounts",
      showIf: { question: "credit_terms", equals: true },
    },
    {
      id: "price_list",
      label: "How do people get prices?",
      input: "single_select",
      options: ["On request", "Published price list", "Priced per customer"],
      prefillFrom: "policies.pricing",
    },
  ],
};

export const RETAIL: Vertical = {
  id: "retail",
  label: "Shop or online store",
  blurb: "Selling products to customers, online or in store",
  match: ["retail", "shop", "store", "ecommerce", "e-commerce", "boutique", "fashion", "clothing", "cosmetic", "furniture", "electronics"],
  questions: [
    {
      id: "products_catalog",
      label: "Add your products",
      help: "Upload a product list, a photo of your price list, or paste it as text. You will review everything before it saves.",
      input: "catalog",
      catalog: {
        noun: "product list",
        itemNoun: "product",
        attributeHints: ["SKU", "size", "colour", "brand", "stock"],
        pastePlaceholder: "Wheel 67 — 120, Brake pads 45, فلتر زيت 15",
      },
      important: true,
    },
    {
      id: "delivery_areas",
      label: "Where do you deliver?",
      input: "chips",
      options: [],
      allowCustom: true,
      placeholder: "Add a city or area you deliver to…",
      important: true,
      prefillFrom: "policies.shipping",
    },
    {
      id: "delivery_fee",
      label: "What does delivery cost?",
      input: "price_range",
    },
    {
      id: "free_delivery_over",
      label: "Free delivery above a certain amount?",
      input: "short_text",
      placeholder: "Free over $50 — or leave empty",
    },
    {
      id: "delivery_time",
      label: "How long does delivery take?",
      input: "single_select",
      options: ["Same day", "1–2 days", "3–5 days", "About a week", "Depends on the area"],
      important: true,
    },
    {
      id: "accepts_returns",
      label: "Do you accept returns?",
      input: "switch",
      prefillFrom: "policies.refunds",
    },
    {
      id: "return_window",
      label: "Within how long?",
      input: "single_select",
      options: ["7 days", "14 days", "30 days", "Case by case"],
      showIf: { question: "accepts_returns", equals: true },
    },
    {
      id: "return_condition",
      label: "What condition must items be in?",
      input: "short_text",
      placeholder: "Unused, with tags and receipt",
      showIf: { question: "accepts_returns", equals: true },
    },
    {
      id: "exchanges",
      label: "Do you do exchanges?",
      input: "single_select",
      options: ["Same rules as returns", "Exchange only, no refunds", "No exchanges"],
    },
    {
      id: "has_shop",
      label: "Do you have a physical shop?",
      input: "switch",
    },
    {
      id: "shop_address",
      label: "Where is it?",
      input: "short_text",
      placeholder: "Street, area, city",
      showIf: { question: "has_shop", equals: true },
    },
    {
      id: "order_tracking",
      label: "Can customers track their order?",
      input: "switch",
    },
  ],
};

export const RESTAURANT: Vertical = {
  id: "restaurant",
  label: "Restaurant or food",
  blurb: "Restaurants, cafés, bakeries, catering, cloud kitchens",
  match: ["restaurant", "food", "cafe", "café", "coffee", "bakery", "catering", "kitchen", "dining", "pizza", "burger", "sushi"],
  questions: [
    {
      id: "menu_catalog",
      label: "Add your menu",
      help: "Upload a photo or PDF of the menu, a spreadsheet, or paste it as text. You will review everything before it saves.",
      input: "catalog",
      catalog: {
        noun: "menu",
        itemNoun: "dish",
        attributeHints: ["section", "portion size", "spice level", "allergens"],
        pastePlaceholder: "Margherita 12, Chicken shawarma 8.50, فتوش 7",
      },
      important: true,
    },
    {
      id: "service_types",
      label: "How do you serve customers?",
      input: "chips",
      options: ["Delivery", "Pickup / takeaway", "Dine-in", "Catering"],
      allowCustom: true,
      important: true,
    },
    {
      id: "delivery_areas",
      label: "Where do you deliver?",
      input: "chips",
      options: [],
      allowCustom: true,
      placeholder: "Add a neighbourhood or city…",
      showIf: { question: "service_types" },
      prefillFrom: "policies.shipping",
    },
    {
      id: "min_order",
      label: "Is there a minimum order?",
      input: "price_range",
    },
    {
      id: "takes_reservations",
      label: "Do you take reservations?",
      input: "switch",
    },
    {
      id: "reservation_channels",
      label: "How can people reserve?",
      input: "chips",
      options: ["Phone", "WhatsApp", "Online", "Walk-in only"],
      allowCustom: true,
      showIf: { question: "takes_reservations", equals: true },
    },
    {
      id: "busy_times",
      label: "When are you busiest?",
      help: "Your AI can warn customers about a wait instead of over-promising.",
      input: "chips",
      options: ["Weekday lunch", "Weekday evening", "Weekend lunch", "Weekend evening", "Holidays"],
      allowCustom: true,
    },
    {
      id: "dietary",
      label: "Which dietary options do you offer?",
      input: "chips",
      options: ["Vegetarian", "Vegan", "Gluten-free", "Halal", "Nut-free options"],
      allowCustom: true,
    },
    {
      id: "menu_link",
      label: "Where can people see the menu?",
      input: "short_text",
      placeholder: "https://…",
    },
  ],
};

export const SERVICES: Vertical = {
  id: "services",
  label: "Services or professional",
  blurb: "Agencies, salons, lawyers, accountants, repairs, trades",
  match: ["service", "agency", "consult", "law", "legal", "account", "salon", "spa", "barber", "repair", "maintenance", "marketing", "design", "software", "cleaning", "photograph"],
  questions: [
    {
      id: "services_catalog",
      label: "Add your service list",
      help: "Upload a price list or paste it as text. You will review everything before it saves.",
      input: "catalog",
      catalog: {
        noun: "service list",
        itemNoun: "service",
        attributeHints: ["unit", "rate type", "minimum charge"],
        pastePlaceholder: "AC service 150/unit, Duct cleaning 400, Callout 75",
      },
      important: true,
    },
    {
      id: "services",
      label: "What services do you offer?",
      input: "list",
      placeholder: "Add a service…",
      important: true,
      prefillFrom: "identity.offerings",
    },
    {
      id: "how_to_start",
      label: "How does a new client start with you?",
      input: "single_select",
      options: ["Send an enquiry", "Call us", "WhatsApp us", "Book online", "Visit us"],
      important: true,
    },
    {
      id: "pricing_model",
      label: "How do you charge?",
      input: "single_select",
      options: ["Per project", "Hourly", "Monthly retainer", "Fixed price list", "Depends on the job"],
      prefillFrom: "policies.pricing",
    },
    {
      id: "typical_price",
      label: "What's a typical price?",
      help: "Only if you're comfortable with your AI sharing a range.",
      input: "price_range",
    },
    {
      id: "free_consultation",
      label: "Do you offer a free first consultation?",
      input: "switch",
    },
    {
      id: "turnaround",
      label: "How long does a typical job take?",
      input: "single_select",
      options: ["Same day", "A few days", "1–2 weeks", "A month or more", "Depends entirely"],
    },
    {
      id: "service_area",
      label: "Where do you work?",
      input: "chips",
      options: ["Remote / online", "At the client's site"],
      allowCustom: true,
      placeholder: "Add a city or region you work in…",
    },
    {
      id: "requires_deposit",
      label: "Do you take a deposit before starting?",
      input: "switch",
    },
    {
      id: "deposit_detail",
      label: "How much?",
      input: "short_text",
      placeholder: "50% upfront",
      showIf: { question: "requires_deposit", equals: true },
    },
  ],
};

export const REAL_ESTATE: Vertical = {
  id: "real_estate",
  label: "Real estate or property",
  blurb: "Agencies, brokers, developers, property management",
  match: ["real estate", "property", "realty", "broker", "estate agent", "developer", "rental", "letting", "apartment"],
  questions: [
    {
      id: "listings_catalog",
      label: "Add your listings",
      help: "Upload a listings sheet, a PDF, or paste them as text. You will review everything before it saves.",
      input: "catalog",
      catalog: {
        noun: "listings",
        itemNoun: "listing",
        attributeHints: ["bedrooms", "area", "community", "furnishing", "reference"],
        pastePlaceholder: "Studio JVC 45k, 1BR Marina 85k, 2BR JBR 140k",
      },
      important: true,
    },
    {
      id: "deal_types",
      label: "Do you handle sales, rentals, or both?",
      input: "chips",
      options: ["For sale", "For rent", "Short-term / holiday lets", "Commercial", "Land"],
      allowCustom: true,
      important: true,
    },
    {
      id: "areas_covered",
      label: "Which areas do you cover?",
      input: "chips",
      options: [],
      allowCustom: true,
      placeholder: "Add a district, city or emirate…",
      important: true,
    },
    {
      id: "property_types",
      label: "What kinds of property?",
      input: "chips",
      options: ["Apartments", "Villas / houses", "Offices", "Retail space", "Warehouses", "Land"],
      allowCustom: true,
      prefillFrom: "identity.offerings",
    },
    {
      id: "budget_range",
      label: "What budgets do you typically work with?",
      help: "Helps your AI tell early whether an enquiry is a fit.",
      input: "price_range",
    },
    {
      id: "qualify_questions",
      label: "What must you know before arranging a viewing?",
      help: "Your AI will ask these before passing the lead to you.",
      input: "chips_plus_text",
      options: [
        "Budget",
        "Preferred area",
        "Number of bedrooms",
        "Buying or renting",
        "Move-in date",
        "Financing or cash",
        "Viewing availability",
      ],
      allowCustom: true,
      placeholder: "Anything else you always ask…",
      important: true,
    },
    {
      id: "viewing_process",
      label: "How are viewings arranged?",
      input: "single_select",
      options: [
        "We call to schedule",
        "Booked directly with the agent",
        "Open viewing times",
        "Owner must approve first",
      ],
    },
    {
      id: "viewing_notice",
      label: "How much notice do you need for a viewing?",
      input: "single_select",
      options: ["Same day possible", "24 hours", "48 hours", "Depends on the owner"],
    },
    {
      id: "commission",
      label: "What is your commission?",
      help: "Leave blank if you'd rather your AI never discusses it.",
      input: "short_text",
      placeholder: "One month's rent, or 2.5% of the sale price",
    },
    {
      id: "listings_link",
      label: "Where can people see your listings?",
      input: "short_text",
      placeholder: "https://…",
    },
    {
      id: "exclusive_listings",
      label: "Do you work with exclusive listings?",
      input: "switch",
    },
  ],
};

export const OTHER: Vertical = {
  id: "other",
  label: "Something else",
  blurb: "Tell us in your own words — nothing here is forced",
  match: [],
  questions: [
    {
      id: "catalog",
      label: "Add your price list or catalog",
      help: "If you sell anything with set prices, upload or paste it here. You will review everything before it saves.",
      input: "catalog",
      catalog: {
        noun: "catalog",
        itemNoun: "item",
        attributeHints: ["unit", "category"],
        pastePlaceholder: "Item name — price, one per line",
      },
      important: true,
    },
    {
      id: "offerings",
      label: "What do you sell or offer?",
      input: "list",
      placeholder: "Add one…",
      important: true,
      prefillFrom: "identity.offerings",
    },
    {
      id: "common_questions",
      label: "What do customers ask you most often?",
      help: "Add the questions; you can add the answers in Knowledge afterwards.",
      input: "list",
      placeholder: "Add a question…",
      important: true,
    },
    {
      id: "how_to_buy",
      label: "How does someone buy from you or get started?",
      input: "long_text",
      important: true,
    },
    {
      id: "location",
      label: "Where are you based, or where do you serve?",
      input: "short_text",
    },
    {
      id: "pricing_note",
      label: "How does pricing work?",
      input: "long_text",
      placeholder: "Fixed prices, quotes on request, depends on the job…",
      prefillFrom: "policies.pricing",
    },
    {
      id: "anything_else",
      label: "Anything else your AI should know?",
      input: "long_text",
    },
  ],
};

export const VERTICALS: readonly Vertical[] = [
  RETAIL,
  RESTAURANT,
  SERVICES,
  CLINIC,
  DISTRIBUTOR,
  REAL_ESTATE,
  OTHER,
];
